services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  legacy_context:
    class: Context
    factory: ['Context','getContext']

  CubaDevOps\Skeleton\Application\ConfigurationRepository:
    class: CubaDevOps\Skeleton\Application\ConfigurationRepository
    arguments:
      - '@legacy_context'

  CubaDevOps\Skeleton\Application\MigrationsLoader:
    class: CubaDevOps\Skeleton\Application\MigrationsLoader

  CubaDevOps\Skeleton\EventSubscriber\InstallerManager:
    class: CubaDevOps\Skeleton\EventSubscriber\InstallerManager
    arguments:
      - '@CubaDevOps\Skeleton\Application\MigrationsLoader'
    tags:
      - { name: kernel.event_subscriber }