services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  legacy_context:
    class: Context
    factory: ['Context','getContext']

  CubaDevOps\Skeleton\Application\ConfigurationRepository:
    class: CubaDevOps\Skeleton\Application\ConfigurationRepository
    arguments:
      - '@legacy_context'